eventstream/event/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls.defaults import *

from event.models import Event

urlpatterns = patterns(
    'event.views',
    url(r'^new$', 'create', name='create'),
    url(r'^(?P<event_id>\d+)$', 'detail', name='detail'),
    url(r'^(?P<event_id>\d+)/edit$', 'edit', name='edit'),
    url(r'^(?P<event_id>\d+)/delete$', 'delete', name='delete'),
    url(r'^(?P<event_id>\d+)/participate$', 'participate', name='participate'),
    )

# 一覧系
now_list_dict = {
    'queryset': Event.objects.now_events(),
    'template_name': 'event/now_list.html',
    'paginate_by': 100,
    }
today_list_dict = {
    'queryset': Event.objects.today_events(),
    'template_name': 'event/today_list.html',
    'paginate_by': 100,
    }
new_list_dict = {
    'queryset': Event.objects.new_events(),
    'template_name': 'event/new_list.html',
    'paginate_by': 100,
    }
urlpatterns += patterns(
    '',
    url(r'^list/now/$', 'django.views.generic.list_detail.object_list', now_list_dict, name='now_list'),
    url(r'^list/today/$', 'django.views.generic.list_detail.object_list', today_list_dict, name='today_list'),
    url(r'^list/new/$', 'django.views.generic.list_detail.object_list', new_list_dict, name='new_list'),
    )

eventstream/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    (r'^auth/', include('auth.urls', namespace="auth")),
    (r'^account/', include('account.urls', namespace="account")),
    (r'^admin/', include(admin.site.urls)),

    (r'^event/', include('event.urls', namespace="event")),
    (r'', include('core.urls', namespace="core")),
)

# static files for debug
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'', include('staticfiles.urls')),
    )

eventstream/event/models.py
# -*- coding: utf-8 -*-
from datetime import datetime, date, timedelta

from django.db import models
from django.core.validators import MinValueValidator
from django.db.models.signals import pre_save

from commons.decorators import cached_property
from commons.utils import maps
from account.models import Account

__all__ = (
    'Event',
    'Participation',
)

class EventManager(models.Manager):
    """
    イベントマネージャ
    """
    def managing_by_account(self, account):
        """
        指定アカウント主催のイベント取得
        """
        return self.filter(user=account)

    def attending_by_account(self, account):
        """指定アカウントの参加イベント取得
        """
        return self.filter(participation__user=account, participation__is_cancelled=False)

    def cancelling_by_account(self, account):
        """指定アカウントのキャンセルイベント取得
        """
        return self.filter(participation__user=account, participation__is_cancelled=True)

    def now_events(self, now=None):
        """現在開催中のイベントを開催日時が古い順に取得
        """
        if now is None:
            now = datetime.now()
        return self.filter(started_at__lte=now, ended_at__gt=now).order_by('started_at')

    def today_events(self, today=None):
        """本日開催のイベントを開催日時が古い順に取得
        """
        if today is None:
            today = date.today()
        tommorow = today + timedelta(1)
        return self.filter(started_at__gte=today, started_at__lt=tommorow).order_by('started_at')

    def new_events(self):
        """最新登録されたイベントを作成日時が古い順に取得
        """
        return self.all().order_by('-created_at')

class Event(models.Model):
    """
    イベントモデル
    """
    objects = EventManager()

    user = models.ForeignKey(Account)
    name = models.CharField(u'タイトル', max_length=255)
    description = models.TextField(u'説明', max_length=1000, blank=True)
    body = models.TextField(u'内容', max_length=1000)
    member_limit = models.IntegerField(u'定員', validators=[MinValueValidator(1)], blank=True, null=True)
    place = models.CharField(u'会場', max_length=255, blank=True, null=True)
    address = models.CharField(u'住所', max_length=255, blank=True, null=True)
    hashtag = models.CharField(u'Twitterハッシュタグ', max_length=100, blank=True, null=True)
    started_at = models.DateTimeField(u'開始日時', default=datetime.now)
    ended_at = models.DateTimeField(u'終了日時', default=datetime.now)
    created_at = models.DateTimeField(u'作成日時', default=datetime.now)
    # googlemaps
    lat = models.DecimalField('lat', max_digits=15, decimal_places=12, blank=True, null=True)
    lng = models.DecimalField('lng', max_digits=15, decimal_places=12, blank=True, null=True)

    participants = models.ManyToManyField(
        Account,
        verbose_name=u"参加者",
        through="Participation",
        related_name="user_events",
        blank=True,
        null=True,
    )

    @cached_property
    def participants_count(self):
        """
        参加希望のカウント
        """
        return self.participation_set.attending().count()

    @cached_property
    def attendants(self):
        """
        正規 参加者
        """
        return self.participation_set.attending()[:self.member_limit] if self.member_limit > 0 else self.participation_set.none()

    @cached_property
    def waiting_list(self):
        """
        キャンセル待ち
        """
        return self.participation_set.attending()[self.member_limit:] if self.member_limit > 0 else self.participation_set.attending()

    @cached_property
    def cancelled(self):
        """
        キャンセルリスト
        """
        return self.participation_set.cancelled()
    
    @cached_property
    def cancelled_count(self):
        return len(self.waiting_list)

    @property
    def googlemaps_image_url(self):
        """
        googlemapsの画像URLを返す
        """
        if self.lat and self.lng:
            return maps.get_static_image_url(self.lat, self.lng)

    @property
    def googlemaps_search_url(self):
        """
        googlemapsの検索結果へのURLを返す
        """
        if self.lat and self.lng:
            return maps.get_search_url(self.lat, self.lng, self.address)

    @models.permalink
    def get_absolute_url(self):
        return ('event:detail', (self.id,), {}) 

    class Meta:
        db_table = 'event'
        verbose_name = verbose_name_plural = u'イベント'
        ordering = ['-started_at']

    def __unicode__(self):
        return u'%s: %s' % (self.id, self.name)

class ParticipationManager(models.Manager):
    def attending(self):
        """参加情報取得
        """
        return self.filter(is_cancelled=False).order_by('utime')

    def cancelled(self):
        """キャンセル情報取得
        """
        return self.filter(is_cancelled=True).order_by('utime')

class Participation(models.Model):
    """イベント参加管理モデル
    """
    user = models.ForeignKey(Account, verbose_name=u"参加者")
    event = models.ForeignKey(Event, verbose_name=u"イベント")
    comment = models.TextField(u'コメント', max_length=1000, blank=True)
    is_cancelled = models.BooleanField(u"キャンセル？", default=False)
    
    ctime = models.DateTimeField(u'作成日時', default=datetime.now, db_index=True)
    utime = models.DateTimeField(u'更新日時', auto_now=True, db_index=True)

    objects = ParticipationManager()

    class Meta:
        db_table = 'event_participation'
        verbose_name = verbose_name_plural = u'イベント参加'
        unique_together = (("user", "event"),)
        ordering = ['is_cancelled', 'utime']

    def __unicode__(self):
        return u'%s (%s)' % (self.event, self.user)

def update_event_lat_lng(sender, instance, **kwargs):
    """
    lat, lngを保存前に更新する
    """
    if instance.address:
        # 検索に失敗してもエラーを出さない
        lat, lng = maps.get_lat_lng(instance.address, silent=True)
        instance.lat = lat
        instance.lng = lng
pre_save.connect(update_event_lat_lng, sender=Event)

eventstream/event/forms.py
# -*- coding:utf-8 -*-
from django import forms

from event.models import Event, Participation

__all__ = (
    'EventForm',
    'ParticipateForm',
)

class EventForm(forms.ModelForm):
    """イベント登録フォーム
    """
    def clean_ended_at(self):
        """開始日時 < 終了日時バリデート
        """
        st = self.cleaned_data['started_at']
        ed = self.cleaned_data['ended_at']
        if st >= ed:
            raise forms.ValidationError(u'終了日時は開始日時以降に設定して下さい。')
        return ed

    class Meta:
        model = Event
        exclude = ('user','participants', 'lat', 'lng', 'created_at')

class ParticipateForm(forms.ModelForm):
    is_cancelled=forms.BooleanField(widget=forms.HiddenInput, required=False)
    class Meta:
        model = Participation
        fields = ('comment','is_cancelled')

eventstream/event/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import redirect
from django.views.generic.simple import direct_to_template
from django.views.decorators.http import require_http_methods

from account.decorators import account_required

from commons.shortcuts import get_object_or_None

from event.decorators import event_view, owner_required
from event.forms import *
from event.models import * 

@require_http_methods(["GET", "HEAD", "POST"])
@account_required
def create(request):
    """
    イベント新規作成
    """

    frm = EventForm(request.POST or None)

    if request.method == 'POST' and frm.is_valid():
        event = frm.save(commit=False)
        event.user = request.account
        event.save()
        return redirect(event)

    return direct_to_template(request, 'event/create.html', {
        'frm': frm,
     })

@require_http_methods(["GET", "HEAD"])
@event_view
def detail(request, event):
    """
    指定イベントの閲覧
    """
    user_participation = get_object_or_None(Participation, user=request.account, event=event)
    # フォーム用 今の状態と逆
    is_cancelled = not user_participation.is_cancelled if user_participation else False
    return direct_to_template(request, 'event/detail.html', {
        'participate_form': ParticipateForm(initial={'is_cancelled': is_cancelled}),
        'user_participation': user_participation,
        'event': event,
    })

@require_http_methods(["GET", "HEAD", "POST"])
@account_required
@event_view
@owner_required
def edit(request, event):
    """
    指定イベントの編集
    """

    frm = EventForm(request.POST or None, instance=event)
    if request.method == 'POST' and frm.is_valid():
        event = frm.save(commit=False)
        event.save()
        return redirect(event)

    return direct_to_template(request, 'event/edit.html', {
        'frm': frm,
    })

@require_http_methods(["POST"])
@account_required
@event_view
@owner_required
def delete(request, event):
    """
    指定イベントの削除
    """
    event.delete()
    return redirect('core:index')

@require_http_methods(["POST"])
@account_required
@event_view
def participate(request, event):
    p = get_object_or_None(Participation, user=request.account, event=event)
    if p:
        form = ParticipateForm(request.POST, instance=p)
    else:
        form = ParticipateForm(request.POST)
    if form.is_valid():
        p = form.save(commit=False)
        p.user = request.account
        p.event = event
        p.save()
    return redirect(event) # イベント詳細ページ

templates/event/create.html
{% extends "base.html" %}

{% block title %}イベントを新規追加{% endblock %}

{% block content %}
<h1>イベントを新規追加</h1>

<form action="" method="POST">
{{ frm.as_p }}
{% csrf_token %}
<input type="submit" value="新規作成">
</form>
{% endblock %}

templates/event/detail.html
{% extends "base.html" %}

{% block title %}{{ event.name }}{% endblock %}

{% block content %}
<div id="event-detail">
  <div class="event-main-contents">
    <h1 class="event-title">{{ event.name }}</h1>

    <div class="event-description">{{ event.description|linebreaksbr }}</div>

    <div class="event-details">
      {% if event.googlemaps_image_url %}
      <div class="event-map">
        <a href="{{ event.googlemaps_search_url }}" target="_blank">
          <img src="{{ event.googlemaps_image_url }}" alt="{{ event.address }}" />
        </a>
      </div>
      {% endif %}
      <dl class="event-data">
        <dt>日時</dt>
        <dd>{{ event.started_at }} - {{ event.ended_at }}</dd>

        {% if event.member_limit %}
        <dt>定員</dt>
        <dd>{{ event.member_limit }}人</dd>
        {% endif %}

        {% if event.place or event.address %}
        <dt>会場</dt>
        <dd>
        {% if event.place %}{{ event.place }}{% if event.address %}({{ event.address }}){% endif %}{% else %}{{ event.address }}{% endif %}{% if event.googlemaps_search_url %} <a href="{{ event.googlemaps_search_url }}">地図</a>{% endif %}</dd>
        {% endif %}

        {% if event.hashtag %}
        <dt>ハッシュタグ</dt>
        <dd><a href="http://twitter.com/#search?q={{ event.hashtag|urlencode }}">{{ event.hashtag }}</a></dd>
        {% endif %}

        <dt>管理者</dt>
        <dd>{{ event.user.username }}</dd>
      </dl>
      <div class="clear"></div>
    </div>

    <div class="event-body">{{ event.body|linebreaks }}</div>

    {% if request.account == event.user %}
    <form action="{% url event:delete event.id %}" method="POST">
      <div class="event-actions">
        <a href="{% url event:edit event.id %}">編集</a> |
          <input type="submit" name="delete" value="削除">
          {% csrf_token %}
      </div>
    </form>
    {% endif %}

    {% if event.hashtag %}
    <div class="twitter-widget">
      <script src="http://widgets.twimg.com/j/2/widget.js"></script>
      <script>
      new TWTR.Widget({
        version: 2,
        type: 'search',
        search: '{{ event.hashtag }}',
        interval: 6000,
        title: '',
        subject: '{{ event.name }}',
        width: 650,
        height: 600,
        theme: {
          shell: {
            background: '#8ec1da',
            color: '#ffffff'
          },
          tweets: {
            background: '#ffffff',
            color: '#444444',
            links: '#1985b5'
          }
        },
        features: {
          scrollbar: false,
          loop: true,
          live: true,
          hashtags: true,
          timestamp: true,
          avatars: true,
          toptweets: true,
          behavior: 'default'
        }
      }).render().start();
      </script>
    </div>
    {% endif %}
  </div>

  <div class="sidebar">
    {% if request.account %}
    コメントを入力してください：
    <form action="{% url event:participate event.id %}" method="POST">
      <textarea id="id_comment" name="comment" rows="5" cols="25"></textarea>
      {{ participate_form.is_cancelled }}
      <input type="submit" name="participate" value="{% if user_participation and not user_participation.is_cancelled %}参加キャンセル{% else %}参加{% endif %}"/>
      {% csrf_token %}
    </form>
    {% else %}
    <form action="{% url auth:login %}" method="GET">
      <input type="submit" name="participate" value="参加"/>
    </form>
    {% endif %}

    <div class="participant-details-block">
      このイベントの参加希望者
      <span class="participant-details{% if event.member_limit and event.participants_count >= event.member_limit %} bad{% else %} good {% endif %}">
        <span class<span class="participant-count">{{ event.participants_count }}</span>{% if event.member_limit %} / <span class="member-limit">{{ event.member_limit }}{% endif %}</span>
      </span>
    </div>

    {% if event.attendants %}
    <h2>参加者</h2>

    <div class="participants">
      {% for participant in event.attendants %}
      <div class="participant">
        {{ forloop.counter }}. <a href="{% url account:detail participant.user.id %}" class="username">{{ participant.user.username }}</a>
        <div class="comment">{{ participant.comment }}</div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    {% if event.waiting_list %}
    <h2>キャンセル待ち</h2>

    <div class="participants">
      {% for participant in event.waiting_list %}
      <div class="participant">
        {{ forloop.counter }}. <a href="{% url account:detail participant.user.id %}" class="username">{{ participant.user.username }}</a>
        <div class="comment">{{ participant.comment }}</div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

    {% if event.cancelled %}
    <h2>キャンセル</h2>

    <div class="participants">
      {% for participant in event.cancelled %}
      <div class="participant">
        {{ forloop.counter }}. <a href="{% url account:detail participant.user.id %}" class="username">{{ participant.user.username }}</a>
        <div class="comment">{{ participant.comment }}</div>
      </div>
      {% endfor %}
    </div>
    {% endif %}

  </div>
  <div class="clear"></div>
</div>
{% endblock %}

templates/event/edit.html
{% extends "base.html" %}

{% block title %}イベントを編集{% endblock %}

{% block content %}
<h1>イベントを編集</h1>

<form action="" method="POST">
{{ frm.as_p }}
{% csrf_token %}
<input type="submit" value="変更を保存">
</form>
{% endblock %}

templates/event/new_list.html
{% extends "base.html" %}

{% block content %}
<h1>最新の登録イベント</h1>

<div>
  {% if object_list %}
  <dl class="event">
    {% for event in object_list %}
    <dt>{{ event.started_at }}</dt>
    <dd><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></dd>
    {% endfor %}
  </dl>

  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
      {% endif %}
      <span class="current">
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
      </span>
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
      {% endif %}
    </span>
  </div>
  {% else %}
  最新の登録イベントはありません
  {% endif %}
</div>
{% endblock %}

templates/event/now_list.html
{% extends "base.html" %}

{% block content %}
<h1>現在開催中のイベント</h1>

<div>
  {% if object_list %}
  <dl class="event">
    {% for event in object_list %}
    <dt>{{ event.started_at }}</dt>
    <dd><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></dd>
    {% endfor %}
  </dl>

  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
      {% endif %}
      <span class="current">
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
      </span>
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
      {% endif %}
    </span>
  </div>
  {% else %}
  現在開催中のイベントはありません
  {% endif %}
</div>
{% endblock %}

templates/event/today_list.html
{% extends "base.html" %}

{% block content %}
<h1>本日開催のイベント</h1>

<div>
  {% if object_list %}
  <dl class="event">
    {% for event in object_list %}
    <dt>{{ event.started_at }}</dt>
    <dd><a href="{{ event.get_absolute_url }}">{{ event.name }}</a></dd>
    {% endfor %}
  </dl>

  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
      {% endif %}
      <span class="current">
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
      </span>
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
      {% endif %}
    </span>
  </div>
  {% else %}
  本日開催のイベントはありません
  {% endif %}
</div>
{% endblock %}